// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpzoafrviednzjctxaxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwem9hZnJ2aWVkbnpqY3R4YXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzI0NjUsImV4cCI6MjA2NTE0ODQ2NX0.xm1ISvNAa5o_wVBQdtqNacSKeTtS76xDlxFkmTeDwrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);